# YOLOv8n config for training on custom dataset

# Model architecture
backbone:
  - type: CSPDarknet
    depth_multiple: 0.33
    width_multiple: 0.50
    filters: [64, 128, 256, 512, 1024]

neck:
  - type: YOLOPAFPN
    filters: [128, 256, 512, 1024]
    depth_multiple: 0.33
    width_multiple: 0.50

head:
  - type: YOLOHead
    filters: [128, 256, 512, 1024]
    depth_multiple: 0.33
    width_multiple: 0.50

# Training settings
train:
  img_size: 640
  batch_size: 16
  epochs: 50
  workers: 4
  device: 0
  data: data/dataset.yaml # path to dataset config file
  weights: "" # path to weights file, if any

# Optimization settings
optimizer:
  type: SGD
  lr0: 0.01
  momentum: 0.937
  weight_decay: 0.0005

# Augmentation settings
augmentation:
  hsv_h: 0.015
  hsv_s: 0.7
  hsv_v: 0.4
  flipud: 0.0
  fliplr: 0.5
  mosaic: 1.0
  mixup: 0.2
  degrees: 0.0
  translate: 0.1
  scale: 0.5
  shear: 0.0
  perspective: 0.0

# Dataset settings
data:
  path: data_1/ # base path for datasets
  train: data_1/images/train
  val: data_1/images/val
  test: data_1/images/test
  nc: 6 # number of classes
  names: ["Scratch", "Dirt", "Bird Dropping", "Rust", "Dent", "Broken"]

# Testing settings
test:
  img_size: 640
  batch_size: 16
  workers: 4
